In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample_sub = pd.read_csv('gender_submission.csv')
test_ids = test['PassengerId']

In [3]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [5]:
#train['Sex'].replace({'male':1,'female': 0}, inplace=True)
#test['Sex'].replace({'male':1,'female': 0}, inplace=True)

In [6]:
#train['Age'].fillna(train.groupby(['Pclass', 'Sex'])['Age'].transform('median'), inplace=True)
#test['Age'].fillna(test.groupby(['Pclass', 'Sex'])['Age'].transform('median'), inplace=True)

In [7]:
#train['Embarked'] = train['Embarked'].fillna('U')
#test['Embarked'] =  test['Embarked'].fillna('U')
#train['Embarked'].replace({'C':0,'Q': 1, 'S':2,'U': 3}, inplace=True)
#test['Embarked'].replace({'C':0,'Q': 1, 'S':2,'U': 3}, inplace=True)

In [8]:
#train['Relatives'] = train.apply(lambda row: int((row['SibSp'] + row['Parch'])>0), axis =1)
#test['Relatives'] = test.apply(lambda row: int((row['SibSp'] + row['Parch'])>0), axis =1)

In [9]:
#train['Fare'].fillna(train.groupby(['Pclass', 'Embarked'])['Fare'].transform('median'), inplace=True)
#test['Fare'].fillna(test.groupby(['Pclass', 'Embarked'])['Fare'].transform('median'), inplace=True)

In [10]:
def clean (data):
    data['Sex'].replace({'male':1,'female': 0}, inplace=True)
    data['Age'].fillna(data.groupby(['Pclass', 'Sex'])['Age'].transform('median'), inplace=True)
    data['Embarked'] = data['Embarked'].fillna('U')
    return(data)



train = clean(train)
test = clean(test)

In [11]:
def features(data):
    data['Embarked'].replace({'C':0,'Q': 1, 'S':2,'U': 3}, inplace=True)
    data['Relatives'] = data.apply(lambda row: int((row['SibSp'] + row['Parch'])>0), axis =1)
    data['Fare'].fillna(data.groupby(['Pclass', 'Embarked'])['Fare'].transform('median'), inplace=True)

    return(data)

train = features(train)
test = features(test)

In [12]:
train = train.drop(columns =['PassengerId', 'Name', 'Ticket', 'Cabin'])
test = test.drop(columns =['PassengerId', 'Name', 'Ticket', 'Cabin'])

In [13]:
y = train['Survived']

In [14]:
X = train.drop(columns = ['Survived'])

In [15]:
from sklearn.model_selection import train_test_split

train_X,test_X,train_y,test_y = train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_X = scaler.fit_transform(train_X)
test_X = scaler.transform(test_X)

In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=10000)
model.fit(train_X, train_y)

LogisticRegression(max_iter=10000)

In [18]:
train_pred = model.predict(train_X)
test_pred = model.predict(test_X)

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score(train_y,train_pred)

0.8061797752808989

In [20]:
accuracy_score(test_y,test_pred)

0.8100558659217877

In [ ]:
#test

     Pclass  Sex   Age  SibSp  Parch      Fare  Embarked  Relatives
0         3    1  34.5      0      0    7.8292         1          0
1         3    0  47.0      1      0    7.0000         2          1
2         2    1  62.0      0      0    9.6875         1          0
3         3    1  27.0      0      0    8.6625         2          0
4         3    0  22.0      1      1   12.2875         2          1
..      ...  ...   ...    ...    ...       ...       ...        ...
413       3    1  24.0      0      0    8.0500         2          0
414       1    0  39.0      0      0  108.9000         0          0
415       3    1  38.5      0      0    7.2500         2          0
416       3    1  24.0      0      0    8.0500         2          0
417       3    1  24.0      1      1   22.3583         0          1

[418 rows x 8 columns]

:

In [21]:
sub_pred = model.predict(test)

In [22]:
submission = pd.DataFrame({'PassengerId' : test_ids.values, 'Survived' : sub_pred})

In [23]:
submission

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [24]:
submission.to_csv('submission.csv', index = False)

In [25]:
print('complete')

complete